# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title: opr.vc - open privacy
description: Datenschutz - open source privacy
lang: de

# Site subpath, e.g. /blog
baseurl: ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Site base hostname & protocol, e.g. http://example.com
url: "https://opr.vc"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo: oprvc_logo_small.png

navbar:
  sticky: true
  search: true

# Default author settings
author:
  name: Sebastian Hofmann
  title: Jurist & Datenschutzbeauftragter
  avatar: sebastian_hofmann.jpg

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  sebastian:
    name: Sebastian Hofmann
    title: Jurist & Datenschutzbeauftragter
    avatar: sebastian_hofmann.jpg


# Social icons displayed in footer
social:
  email:
  website:
  facebook:
  flickr:
  dribbble:
  github: https://github.com/oprvc/oprvc.github.io/
  googleplus:
  instagram:
  linkedin:
  pinterest:
  twitter: https://twitter.com/opr_vc
  vimeo:
  youtube:

# Share button
share:
  post: false # Display share buttons on a post page
  doc: false # Display share buttons on a doc page
  twitter: username # Enable by adding Twitter handle
  facebook: false # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
  copyright: [opr.vc](https://opr.vc)

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
  shortname: # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path: "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads: /uploads/

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-extlinks
  - jekyll-target-blank
  - jekyll-minifier:
      preserve_php: true                # Default: false
      remove_spaces_inside_tags: true   # Default: true
      remove_multi_spaces: true         # Default: true
      remove_comments: true             # Default: true
      remove_intertag_spaces: true      # Default: false
      remove_quotes: false              # Default: false
      compress_css: true                # Default: true
      compress_javascript: true         # Default: true
      compress_json: true               # Default: true
      simple_doctype: false             # Default: false
      remove_script_attributes: false   # Default: false
      remove_style_attributes: false    # Default: false
      remove_link_attributes: false     # Default: false
      remove_form_attributes: false     # Default: false
      remove_input_attributes: false    # Default: false
      remove_javascript_protocol: false # Default: false
      remove_http_protocol: false       # Default: false
      remove_https_protocol: false      # Default: false
      preserve_line_breaks: false       # Default: false
      simple_boolean_attributes: false  # Default: false
      compress_js_templates: false      # Default: false
      preserve_patterns:                # Default: (empty)
      uglifier_args:                    # Default: (empty)
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
sass:
  style: compressed

collections:
  docs:
    output: true
  faqs:
    output: false
  changelogs:
    output: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: doc